credentials:
  usernames:
    admin:
      name: admin
      password: $2b$12$cTWTIN00RaUPyZAcH9BQRu/NVfhUfKvE7Xj2jpefZVKUi1xZ6r2VW
    participant:
      name: participant
      password: $2b$12$fZmF.qAo5QF6ozlyaupNt.6F1CiV5pHM7XbReH0zfQjNOvO06a11a

cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name